### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by spmcewen** [oiva/homebridge-air-quality-file#3]
I saw the note in readme about changing the date format in aqi.py. When I modified my example aqi.json file to contain what the script would produce (m.d.Y):

```
[
  {"pm25": 1.3, "pm10": 2.9, "time": "03.12.2020 21:23:32"},
  {"pm10": 2.1, "pm25": 1.1, "time": "03.12.2020 22:47:30"}
]
```
Homebridge crashed with this error:

```
Dec  1 14:47:17 homebridge homebridge[21630]: [12/1/2020, 2:47:17 PM] TypeError: Cannot read property 'pm25' of undefined
Dec  1 14:47:17 homebridge homebridge[21630]:     at /usr/lib/node_modules/homebridge-air-quality-file/dist/index.js:172:38
Dec  1 14:47:17 homebridge homebridge[21630]:     at /usr/lib/node_modules/homebridge-air-quality-file/dist/index.js:68:12
Dec  1 14:47:17 homebridge homebridge[21630]:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
Dec  1 14:47:17 homebridge homebridge[21630]: [12/1/2020, 2:47:17 PM] Got SIGTERM, shutting down Homebridge...
```

I changed aqi.json back to
```
[
  {"pm25": 1.3, "pm10": 2.9, "time": "12.03.2020 21:23:32"},
  {"pm10": 2.1, "pm25": 1.1, "time": "12.03.2020 22:47:30"}
]
```

and Homebridge started working again.

Is it still necessary to change the date format?  It seems to work as is, how do the dates affect what is displayed in HomeKit?

**Comment by spmcewen** [comment]
I see why this is. Using the old sample data results in nothing being returned by filterReadings. There is a check that data === null but not that data.length is 0. I'll submit a PR that I think will fix this. I think it's better for the sensor to show no data than to crash all of Homebridge no data makes it through the filter!

Since Dec 3rd is in the future, now - future_date is greater than 3600000 so data is still returned by the filter when I use "12.03.2020 22:47:30" as my sample data. Changing it to March 12th causes the data to be filtered out.

**Comment by sCrunch021** [comment]
I had the same issue! Documented my fix here: https://github.com/oiva/homebridge-air-quality-file/pull/2

**Comment by oiva** [comment]
Thanks @spmcewen for fixing the error resulting from empty data and @sCrunch021 for the documenting the date format fix. I changed the README to now recommend using ISO 8601 format which should work for everyone regardless of local date formats 🙂
