### ISSUE TITLE
Please publish latest code since v1.1.0

### ISSUE THREAD

**Issue by quackyduck** [oiva/homebridge-air-quality-file#7]
v1.1.0 doesn't actually support the HTTP/HTTPS calls that I was trying to use. I noticed you wrote that in the latest code, but you haven't published the latest package. Please do!

**Comment by quackyduck** [comment]
https://www.npmjs.com/package/homebridge-air-quality-file

**Comment by oiva** [comment]
New version (1.1.1) published.
