### ISSUE TITLE
filterReadings doesn't have access to AirQualityFileAccessory.duration_to_average

### ISSUE THREAD

**Issue by quackyduck** [oiva/homebridge-air-quality-file#8]
I'm not quite sure what duration_to_average is trying to do, but you've got a broken test. I found this as I was trying to debug why HTTP/HTTPS wasn't working.

**Comment by quackyduck** [comment]
https://github.com/oiva/homebridge-air-quality-file/pull/9

**Comment by oiva** [comment]
Fixed by #9, thanks!
